In [34]:
import h5py 

def print_h5py_info(obj, name):
    """
    Function to recursively print information about HDF5 file objects.
    """
    print(name)
    if isinstance(obj, h5py.Group):
        for key in obj.keys():
            print_h5py_info(obj[key], name + '/' + key)
    elif isinstance(obj, h5py.Dataset):
        print(f'Dataset shape: {obj.shape}')
        print(f'Dataset dtype: {obj.dtype}')
        # Print dataset attributes
        for attr_name, attr_value in obj.attrs.items():
            print(f'Attribute: {attr_name}, Value: {attr_value}')
    elif isinstance(obj, h5py.AttributeManager):
        # Print attributes of a group
        for attr_name, attr_value in obj.items():
            print(f'Attribute: {attr_name}, Value: {attr_value}')


file = './train.h5'
with h5py.File(file, 'r') as f:
    print_h5py_info(f, '/')

/
//center
Dataset shape: (22246, 2)
Dataset dtype: float64
//imgname
Dataset shape: (22246,)
Dataset dtype: |S13
//index
Dataset shape: (22246,)
Dataset dtype: int64
//name
Dataset shape: ()
Dataset dtype: object
//name_
Dataset shape: ()
Dataset dtype: |S4
//normalize
Dataset shape: (22246,)
Dataset dtype: float64
//part
Dataset shape: (22246, 16, 2)
Dataset dtype: float64
//person
Dataset shape: (22246,)
Dataset dtype: int64
//scale
Dataset shape: (22246,)
Dataset dtype: float64
//torsoangle
Dataset shape: (22246,)
Dataset dtype: float64
//visible
Dataset shape: (22246, 16)
Dataset dtype: float64


In [2]:
with h5py.File(file, 'r') as f:
    print(f['part'][:10])

[[[ 620.  394.]
  [ 616.  269.]
  [ 573.  185.]
  [ 647.  188.]
  [ 661.  221.]
  [ 656.  231.]
  [ 610.  187.]
  [ 647.  176.]
  [ 637.  189.]
  [ 695.  108.]
  [ 606.  217.]
  [ 553.  161.]
  [ 601.  167.]
  [ 692.  185.]
  [ 693.  240.]
  [ 688.  313.]]

 [[ 895.  293.]
  [ 910.  279.]
  [ 945.  223.]
  [1012.  218.]
  [ 961.  315.]
  [ 960.  403.]
  [ 979.  221.]
  [ 906.  190.]
  [ 912.  190.]
  [ 830.  182.]
  [ 871.  304.]
  [ 883.  229.]
  [ 888.  174.]
  [ 924.  206.]
  [1013.  203.]
  [ 955.  263.]]

 [[   0.    0.]
  [   0.    0.]
  [ 806.  543.]
  [ 720.  593.]
  [   0.    0.]
  [   0.    0.]
  [ 763.  568.]
  [ 683.  290.]
  [ 682.  256.]
  [ 676.   68.]
  [ 563.  296.]
  [ 555.  410.]
  [ 647.  281.]
  [ 719.  299.]
  [ 711.  516.]
  [ 545.  466.]]

 [[   0.    0.]
  [   0.    0.]
  [ 987.  607.]
  [1194.  571.]
  [   0.    0.]
  [   0.    0.]
  [1091.  589.]
  [1038.  292.]
  [1025.  261.]
  [ 947.   74.]
  [ 914.  539.]
  [ 955.  470.]
  [ 931.  315.]
  [1145.  269.]
  

In [3]:
with h5py.File(file, 'r') as f:
    print(f['visible'][0])

[1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
with h5py.File(file, 'r') as f:
    print(f['scale'][:10])

[3.77630772 3.09014563 7.05159556 7.58881414 7.16020251 3.35168614
 3.1441374  4.75800378 3.00015    2.69416035]


In [5]:
 with h5py.File(file, 'r') as f:
    print(f['center'][:10])

[[ 594.          302.31569265]
 [ 952.          259.08174753]
 [ 619.          413.61914677]
 [1010.          503.06576964]
 [ 133.          400.92243013]
 [ 291.          393.22023371]
 [ 472.          414.72964882]
 [ 897.          228.0960454 ]
 [ 582.          304.00179996]
 [ 765.          426.32992422]]


In [6]:
 with h5py.File(file, 'r') as f:
    print(f['imgname'][:10])

[b'015601864.jpg' b'015601864.jpg' b'015599452.jpg' b'015599452.jpg'
 b'015599452.jpg' b'086617615.jpg' b'086617615.jpg' b'060111501.jpg'
 b'070807258.jpg' b'070807258.jpg']


In [7]:
import numpy as np

tags = ['imgname','part','center','scale']
annot = {}

with h5py.File(file, 'r') as f:
    for tag in tags:
        annot[tag] = np.asarray(f[tag]).copy()
f.close()

print(f"The length of the dataset is {len(annot['scale'])}")


The length of the dataset is 22246


In [36]:
tags = ['center', 'imgname', 'index', 'normalize',
       'part', 'person', 'scale', 'torsoangle', 'visible']

with h5py.File(file, 'r') as f:
    for i in range(100):
        for tag in tags:
            print(f"{tag}: {f[tag][i]}")
        print("=====================================")

center: [594.         302.31569265]
imgname: b'015601864.jpg'
index: 4
normalize: 75.52615441024388
part: [[620. 394.]
 [616. 269.]
 [573. 185.]
 [647. 188.]
 [661. 221.]
 [656. 231.]
 [610. 187.]
 [647. 176.]
 [637. 189.]
 [695. 108.]
 [606. 217.]
 [553. 161.]
 [601. 167.]
 [692. 185.]
 [693. 240.]
 [688. 313.]]
person: 0
scale: 3.7763077205121935
torsoangle: 73.44292862436335
visible: [1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
center: [952.         259.08174753]
imgname: b'015601864.jpg'
index: 4
normalize: 61.80291255272683
part: [[ 895.  293.]
 [ 910.  279.]
 [ 945.  223.]
 [1012.  218.]
 [ 961.  315.]
 [ 960.  403.]
 [ 979.  221.]
 [ 906.  190.]
 [ 912.  190.]
 [ 830.  182.]
 [ 871.  304.]
 [ 883.  229.]
 [ 888.  174.]
 [ 924.  206.]
 [1013.  203.]
 [ 955.  263.]]
person: 1
scale: 3.0901456276363417
torsoangle: -66.99112991717712
visible: [1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1.]
center: [619.         413.61914677]
imgname: b'015599452.jpg'
index: 5
normalize: 141.0

In [14]:
# Testing

In [15]:
import h5py 

def print_h5py_info(obj, name):
    """
    Function to recursively print information about HDF5 file objects.
    """
    print(name)
    if isinstance(obj, h5py.Group):
        for key in obj.keys():
            print_h5py_info(obj[key], name + '/' + key)
    elif isinstance(obj, h5py.Dataset):
        print(f'Dataset shape: {obj.shape}')
        print(f'Dataset dtype: {obj.dtype}')
        # Print dataset attributes
        for attr_name, attr_value in obj.attrs.items():
            print(f'Attribute: {attr_name}, Value: {attr_value}')
    elif isinstance(obj, h5py.AttributeManager):
        # Print attributes of a group
        for attr_name, attr_value in obj.items():
            print(f'Attribute: {attr_name}, Value: {attr_value}')


file = './test.h5'
with h5py.File(file, 'r') as f:
    print_h5py_info(f, '/')

/
//center
Dataset shape: (11731, 2)
Dataset dtype: float64
//imgname
Dataset shape: (11731,)
Dataset dtype: |S13
//index
Dataset shape: (11731,)
Dataset dtype: int64
//name
Dataset shape: ()
Dataset dtype: object
//normalize
Dataset shape: (11731,)
Dataset dtype: int64
//part
Dataset shape: (11731, 16, 2)
Dataset dtype: float64
//person
Dataset shape: (11731,)
Dataset dtype: int64
//scale
Dataset shape: (11731,)
Dataset dtype: float64
//torsoangle
Dataset shape: (11731,)
Dataset dtype: float64
//visible
Dataset shape: (11731, 16)
Dataset dtype: float64


In [16]:
with h5py.File(file, 'r') as f:
    print(f['part'][:10])

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.

In [17]:
tags = ['center', 'imgname', 'index', 'normalize',
       'part', 'person', 'scale', 'torsoangle', 'visible']

with h5py.File(file, 'r') as f:

        for tag in tags:
            print(f"{tag}: {f[tag][2441]}")
        print("=====================================")

center: [601.         438.21100927]
imgname: b'037454012.jpg'
index: 0
normalize: -1
part: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
person: 0
scale: 4.850917439000585
torsoangle: 0.0
visible: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
center: [881.         515.17249193]
imgname: b'095071431.jpg'
index: 1
normalize: -1
part: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
person: 0
scale: 10.09770766065249
torsoangle: 0.0
visible: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
center: [338.         343.56194069]
imgname: b'095071431.jpg'
index: 1
normalize: -1
part: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
person: 1
scale: 11.130161723892424
torsoangle: 0.0
visible: [0. 0. 0. 0

In [18]:
import h5py 

def print_h5py_info(obj, name):
    """
    Function to recursively print information about HDF5 file objects.
    """
    print(name)
    if isinstance(obj, h5py.Group):
        for key in obj.keys():
            print_h5py_info(obj[key], name + '/' + key)
    elif isinstance(obj, h5py.Dataset):
        print(f'Dataset shape: {obj.shape}')
        print(f'Dataset dtype: {obj.dtype}')
        # Print dataset attributes
        for attr_name, attr_value in obj.attrs.items():
            print(f'Attribute: {attr_name}, Value: {attr_value}')
    elif isinstance(obj, h5py.AttributeManager):
        # Print attributes of a group
        for attr_name, attr_value in obj.items():
            print(f'Attribute: {attr_name}, Value: {attr_value}')


file = './valid.h5'
with h5py.File(file, 'r') as f:
    print_h5py_info(f, '/')

/
//center
Dataset shape: (2958, 2)
Dataset dtype: float64
//imgname
Dataset shape: (2958,)
Dataset dtype: |S13
//index
Dataset shape: (2958,)
Dataset dtype: float64
//normalize
Dataset shape: (2958,)
Dataset dtype: float64
//part
Dataset shape: (2958, 16, 2)
Dataset dtype: float64
//person
Dataset shape: (2958,)
Dataset dtype: float64
//scale
Dataset shape: (2958,)
Dataset dtype: float64
//torsoangle
Dataset shape: (2958,)
Dataset dtype: float64
//visible
Dataset shape: (2958, 16)
Dataset dtype: float64


In [32]:
tags = ['center', 'imgname', 'index', 'normalize',
       'part', 'person', 'scale', 'torsoangle', 'visible']

with h5py.File(file, 'r') as f:

    for tag in tags:
        print(f"{tag}: {f[tag][227]}")
    print("=====================================")

center: [1040.          583.85665966]
imgname: b'011493300.jpg'
index: 2249.0
normalize: 64.76109943476871
part: [[ 994.  844.]
 [ 994.  726.]
 [1006.  559.]
 [1074.  545.]
 [1062.  743.]
 [1060.  854.]
 [1040.  552.]
 [1043.  364.]
 [1045.  338.]
 [1051.  252.]
 [1027.  561.]
 [ 950.  462.]
 [ 990.  359.]
 [1095.  368.]
 [1103.  467.]
 [1047.  508.]]
person: 2.0
scale: 3.2380549717384355
torsoangle: 0.9142167604489941
visible: [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0.]
